default_settings:
  parser_options:
    myapifilms:
      api_key: INSERTHERE

sets:
  - name: GameMusic
    parsers: [vgmdb]
    scan_mode: directories
    source_dir: /media/music/Game Music/Mp3/Albums
    cache_dir: /media/music/Game Music/Mp3/Albums/.cache
    output:
       - dest: /media/music/Game Music/Mp3/Artists
         group_by: [artists, arrangers]
       - dest: /media/music/Game Music/Mp3/Series
         group_by: franchise
  - name: TV
    #fakeclean: true
    parsers: [freebase,quantizer]
    parser_options:
      freebase:
        type: /tv/tv_program
    scan_mode: directories
    source_dir: /media/video/tv/All
    cache_dir: /media/video/tv/.cache
    output:
      - dest: /media/video/tv/Genres
        group_by: genres
      - dest: /media/video/tv/Decades
        group_by: decades
      - dest: /media/video/tv/Writers
        group_by: writers
      - dest: /media/video/actors
        group_by: actors

  - name: Movies
    #fakeclean: true
    parsers: [freebase,quantizer]
    parser_options:
      freebase:
        type: /film/film
    scan_mode: directories
    source_dir: /media/video/movies/All
    cache_dir: /media/video/movies/.cache
    output:
      - dest: /media/video/movies/Genres
        group_by: genres
      - dest: /media/video/movies/Composers
        group_by: composers
      - dest: /media/video/movies/Directors
        group_by: directors
      - dest: /media/video/movies/Decades
        group_by: decades
      - dest: /media/video/movies/Series
        group_by: series
      - dest: /media/video/actors
        group_by: actors

  - name: Songs
    parsers: [id3]
    scan_mode: files
    source_dir: /media/music/Songs
    cache_dir: /tmp/songcache
    regex: \.mp3$
    output:
      - dest: /tmp/songs
        group_by: album
