default_settings:
  parser_options:
    myapifilms:
      api_key: INSERTHERE

sets:
  - name: GameMusic
    parsers: [vgmdb]
    scanMode: directories
    sourceDir: /media/music/Game Music/Mp3/Albums
    cacheDir: /media/music/Game Music/Mp3/Albums/.cache
    output:
       - dest: /media/music/Game Music/Mp3/Artists
         groupBy: [artists, arrangers]
       - dest: /media/music/Game Music/Mp3/Series
         groupBy: franchise
  - name: TV
    #fakeclean: true
    parsers: [freebase,quantizer]
    parser_options:
      freebase:
        type: /tv/tv_program
    scanMode: directories
    sourceDir: /media/video/tv/All
    cacheDir: /media/video/tv/.cache
    output:
      - dest: /media/video/tv/Genres
        groupBy: genres
      - dest: /media/video/tv/Decades
        groupBy: decades
      - dest: /media/video/tv/Writers
        groupBy: writers
      - dest: /media/video/actors
        groupBy: actors

  - name: Movies
    #fakeclean: true
    parsers: [freebase,quantizer]
    parser_options:
      freebase:
        type: /film/film
    scanMode: directories
    sourceDir: /media/video/movies/All
    cacheDir: /media/video/movies/.cache
    output:
      - dest: /media/video/movies/Genres
        groupBy: genres
      - dest: /media/video/movies/Composers
        groupBy: composers
      - dest: /media/video/movies/Directors
        groupBy: directors
      - dest: /media/video/movies/Decades
        groupBy: decades
      - dest: /media/video/movies/Series
        groupBy: series
      - dest: /media/video/actors
        groupBy: actors

  - name: Songs
    parsers: [id3]
    scanMode: files
    sourceDir: /media/music/Songs
    cacheDir: /tmp/songcache
    regex: \.mp3$
    output:
      - dest: /tmp/songs
        groupBy: album
