sets:
  - name: GameMusic
    parsers: [vgmdb]
    scanMode: directories
    sourceDir: /media/music/Game Music/Mp3/Albums
    cacheDir: /media/music/Game Music/Mp3/Albums/.cache
    output:
       - dest: /media/music/Game Music/Mp3/Artists
         groupBy: artists
       - dest: /media/music/Game Music/Mp3/Series
         groupBy: franchise
  - name: TV
#    fakeclean: true
    parsers: [omdbapi,mymovieapi]
    parser_options:
      mymovieapi:
        type: tv series
    scanMode: directories
    sourceDir: /media/video/tv/All
    cacheDir: /media/video/tv/.cache
    preferCachedData: true
    output:
      - dest: /media/video/tv/
        groupBy: genres
      - dest: /media/video/Actors
        groupBy: actors


  - name: MoviesHD
    fakeclean: true
    parsers: [omdbapi,mymovieapi]
    parser_options:
      mymovieapi:
        type: movie
    scanMode: directories
    sourceDir: /media/video/moviesHD
    cacheDir: /media/video/moviesHD/.cache
    preferCachedData: true
    output:
      - dest: /media/video/Actors
        groupBy: actors

  - name: Movies
#    fakeclean: true
    parsers: [omdbapi,mymovieapi]
    parser_options:
      mymovieapi:
        type: movie
    scanMode: directories
    sourceDir: /media/video/movies
    cacheDir: /media/video/movies/.cache
    preferCachedData: true
    output:
      - dest: /media/video/Actors
        groupBy: actors
